
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    trustDomain: example.org
  values:
    # This is used to customize the sidecar template.
    # It adds both the label to indicate that SPIRE should manage the
    # identity of this pod, as well as the CSI driver mounts.
    sidecarInjectorWebhook:
      templates:
        spire: |
          labels:
            spiffe.io/spire-managed-identity: "true"
          spec:
            containers:
            - name: istio-proxy
              volumeMounts:
              - name: workload-socket
                mountPath: /run/secrets/workload-spiffe-uds
                readOnly: true
            volumes:
              - name: workload-socket
                csi:
                  driver: "csi.spiffe.io"
                  readOnly: true
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          overlays:
            # This is used to customize the ingress gateway template.
            # It adds the CSI driver mounts, as well as an init container
            # to stall gateway startup until the CSI driver mounts the socket.
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.volumes.[name:workload-socket]
                  value:
                    name: workload-socket
                    csi:
                      driver: "csi.spiffe.io"
                      readOnly: true
                - path: spec.template.spec.containers.[name:istio-proxy].volumeMounts.[name:workload-socket]
                  value:
                    name: workload-socket
                    mountPath: "/run/secrets/workload-spiffe-uds"
                    readOnly: true
                - path: spec.template.spec.initContainers
                  value:
                    - name: wait-for-spire-socket
                      image: busybox:1.36
                      volumeMounts:
                        - name: workload-socket
                          mountPath: /run/secrets/workload-spiffe-uds
                          readOnly: true
                      env:
                        - name: CHECK_FILE
                          value: /run/secrets/workload-spiffe-uds/socket
                      command:
                        - sh
                        - "-c"
                        - |-
                          echo "$(date -Iseconds)" Waiting for: ${CHECK_FILE}
                          while [[ ! -e ${CHECK_FILE} ]] ; do
                            echo "$(date -Iseconds)" File does not exist: ${CHECK_FILE}
                            sleep 15
                          done
                          ls -l ${CHECK_FILE}



# pid=57919 selectors="[type:\"k8s\" value:\"sa:istio-ingressgateway-service-account\" type:\"k8s\" value:\"ns:istio-system\" type:\"k8s\" value:\"node-name:ip-10-1-1-194.ec2.internal\" type:\"k8s\" value:\"pod-uid:762c871d-6a81-4cdd-882d-ab527fdcbbab\" type:\"k8s\" value:\"pod-name:istio-ingressgateway-d7cdc5b65-nr75m\" type:\"k8s\" value:\"pod-image-count:1\" type:\"k8s\" value:\"pod-init-image-count:1\" type:\"k8s\" value:\"pod-image:docker.io/istio/proxyv2@sha256:445156b5f4a780242d079a47b7d88199cbbb5959c92358469b721af490eca1ae\" type:\"k8s\" value:\"pod-image:docker.io/istio/proxyv2:1.24.2\" type:\"k8s\" value:\"pod-init-image:docker.io/library/busybox@sha256:71b79694b71639e633452f57fd9de40595d524de308349218d9a6a144b40be02\" type:\"k8s\" value:\"pod-init-image:docker.io/library/busybox:1.36\" type:\"k8s\" value:\"pod-label:app:istio-ingressgateway\" type:\"k8s\" value:\"pod-label:app.kubernetes.io/managed-by:Helm\" type:\"k8s\" value:\"pod-label:app.kubernetes.io/version:1.24.2\" type:\"k8s\" value:\"pod-label:chart:gateways\" type:\"k8s\" value:\"pod-label:heritage:Tiller\" type:\"k8s\" value:\"pod-label:app.kubernetes.io/name:istio-ingressgateway\" type:\"k8s\" value:\"pod-label:release:istio\" type:\"k8s\" value:\"pod-label:service.istio.io/canonical-revision:latest\" type:\"k8s\" value:\"pod-label:sidecar.istio.io/inject:false\" type:\"k8s\" value:\"pod-label:app.kubernetes.io/part-of:istio\" type:\"k8s\" value:\"pod-label:helm.sh/chart:istio-ingress-1.24.2\" type:\"k8s\" value:\"pod-label:install.operator.istio.io/owning-resource:unknown\" type:\"k8s\" value:\"pod-label:pod-template-hash:d7cdc5b65\" type:\"k8s\" value:\"pod-label:service.istio.io/canonical-name:istio-ingressgateway\" type:\"k8s\" value:\"pod-label:app.kubernetes.io/instance:istio\" type:\"k8s\" value:\"pod-label:istio:ingressgateway\" type:\"k8s\" value:\"pod-label:istio.io/rev:default\" type:\"k8s\" value:\"pod-label:operator.istio.io/component:IngressGateways\" type:\"k8s\" value:\"pod-owner:ReplicaSet:istio-ingressgateway-d7cdc5b65\" type:\"k8s\" value:\"pod-owner-uid:ReplicaSet:c98d7c64-8783-44e4-a655-02994a791cd5\" type:\"k8s\" value:\"container-name:istio-proxy\" type:\"k8s\" value:\"container-image:docker.io/istio/proxyv2@sha256:445156b5f4a780242d079a47b7d88199cbbb5959c92358469b721af490eca1ae\" type:\"k8s\" value:\"container-image:docker.io/istio/proxyv2:1.24.2\"]" subsystem_name=workload_attestor
# time="2025-01-16T20:25:09Z" level=debug msg="Received StreamSecrets request" 