apiVersion: v1
kind: Config
clusters:
  - name: eks-ec2-mtls-with-spire-istio
    cluster:
      certificate-authority-data: 
      server: https://728C94E42EDA6CCCE90096DC8FB1C135.gr7.us-east-1.eks.amazonaws.com
contexts:
  - name: spire-server@eks-ec2-mtls-with-spire-istio
    context:
      cluster: eks-ec2-mtls-with-spire-istio
      namespace: spire-server
      user: spire-server
users:
  - name: spire-server
    user:
      token: 
      current-context: spire-server@eks-ec2-mtls-with-spire-istio